esphome:
  name: winnie
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "wifi2587"
  password: "Bu1ttCheek41!"

  manual_ip:
    static_ip: 192.168.40.201
    gateway: 192.168.40.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Dual Button"
    on_press:
      - switch.toggle: relay1

switch:
  - platform: gpio
    name: "Sonoff Dual Relay 1"
    pin: GPIO12
    id: relay1
  - platform: gpio
    name: "Sonoff Dual Relay 2" 
    pin: GPIO5
    id: relay2

status_led:
  pin:
    number: GPIO13
    inverted: yes