M48
; DRILL file {KiCad (6.0.8)} date Sat Nov 26 11:41:06 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-26T11:41:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X4.16Y-3.6231
X4.16Y-3.8987
X4.675Y-3.6231
X4.675Y-3.8987
T2
X2.17Y-2.6
X4.3Y-2.775
T0
M30
