M48
; DRILL file {KiCad (5.99.0-11382-g00f1b609c4)} date Sun Aug 15 08:59:10 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-08-15T08:59:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-11382-g00f1b609c4)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.1Y-2.1
X5.1Y-4.0
X6.3998Y-4.0
X6.4Y-2.1
T0
M30
