esphome:
  name: $devicename
  comment: Reptile Controller - ${upper_devicename}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

web_server:
  port: 80

sun:
  latitude: 38.480419
  longitude: -90.322969
  on_sunrise:
    - then:
      - logger.log: Good morning ${upper_devicename}!
      - switch.turn_on: lights
  on_sunset:
    - then:
      - logger.log: Good night ${upper_devicename}!
      - switch.turn_off: lights
        
time:
  - platform: homeassistant

dallas:
  - pin: GPIO01
    update_interval: 15s

sensor:
  - platform: dallas
    index: 0
    id: uth_temperature
    name: "${upper_devicename} - UTH Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 1

climate:
  - platform: bang_bang
    name: "${upper_devicename} - UTH Thermostat"
    sensor: uth_temperature
    visual:
      min_temperature: 25 °C
      max_temperature: 35 °C
      temperature_step: 0.1 °C
    default_target_temperature_low: 31.0 °C
    default_target_temperature_high: 32.5 °C
    heat_action:
      - switch.turn_on: uth
    idle_action:
      - switch.turn_off: uth
      
switch:
  - platform: gpio
    name: "${upper_devicename} - Lights"
    pin: GPIO12
    id: lights
    icon: "mdi:lightbulb"
  - platform: gpio
    name: "${upper_devicename} - UTH" 
    pin: GPIO5
    id: uth
    icon: "mdi:fire"

status_led:
  pin:
    number: GPIO13
    inverted: yes